# Generated by Django 4.2.5 on 2023-11-06 09:22

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryOrAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mda', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('date_on_voucher', models.DateField()),
                ('date_of_voucher_approval', models.DateField()),
                ('approved_by', models.CharField(choices=[('governor', 'Governor'), ('budget', 'Budget'), ('accoutant_general', 'Accountant General')], max_length=50)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=14)),
                ('voucher_code', models.CharField(max_length=50, unique=True)),
                ('upload_voucher', models.FileField(upload_to='media/voucher')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry_or_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.ministryoragency')),
            ],
        ),
    ]
