# Generated by Django 4.2.5 on 2023-09-11 12:34

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=14),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='ministry_or_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.ministryoragency'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
